spring.application.name=notification-service
server.port=8003

# Database config
spring.datasource.url=jdbc:postgresql://postgres-db:5432/db_soporte
spring.datasource.username=user_pfc
spring.datasource.password=password_pfc

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security - Disabled for initial testing
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Connection timeout
spring.datasource.hikari.initialization-fail-timeout=0