events {}
http {
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=100r/m;
    server {
        listen 8080;
        location /api/auth/ {
            limit_req zone=mylimit;
            proxy_pass http://auth-service:8001/;
        }
        location /api/resources/ {
            limit_req zone=mylimit;
            proxy_pass http://resource-service:8002/;
        }
        location /api/notifications/ {
            limit_req zone=mylimit;
            proxy_pass http://notification-service:8003/;
        }
    }
}