spring.application.name=soporte-tecnico-backend
# Puerto del microservicio de Recursos
server.port=8002

# Configuraci�n de PostgreSQL (para Docker)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/db_soporte
spring.datasource.username=user_pfc
spring.datasource.password=password_pfc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar seguridad moment�neamente para probar
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration